menu:


people:

courses:

social:
- {icon: 'github', link: 'https://github.com/ryboselm'}
- {icon: 'twitter', link: 'https://twitter.com/ryboselm'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/ryan-anselm'}

contacts:
